### ISSUE TITLE
ロゴ

### ISSUE THREAD

**Issue by ichiren1** [ichiren1/shouzi#13]
障子とsとhをかたどってる

![products_logo_ver1](https://cloud.githubusercontent.com/assets/4242885/9173373/a8facbf6-3fb4-11e5-83af-5afdc1983e84.png)

**Comment by mizukmb** [comment]
障子感ある

**Comment by ichiren1** [comment]
なんか押すと増えていくはてなのいいねみたいなボタンってどうやってつくるんだっけ

**Comment by mizukmb** [comment]
JavaScriptで実装する

**Comment by ichiren1** [comment]
Github上でできたはずだよ！！！！！！

**Comment by ichiren1** [comment]
- [ ] みたいなかんじで

**Comment by mizukmb** [comment]
どういうこと？
良さボタンのことじゃなくて？

**Comment by ichiren1** [comment]
なんかGithubでコメントで何かを打ったら投票みたいなことできたと思ったんだよなぁ
それ使ってどの色がいいか決めようと思ったんだけど💀

**Comment by mizukmb** [comment]
スタックオーバーフローの Vote みたいな機能のことかなるほど
俺はその辺知らないなー

**Comment by ichiren1** [comment]
:+1:
